// IOBUF.v

// Generated using ACDS version 20.2 50

`timescale 1 ps / 1 ps
module IOBUF (
		output wire [0:0] dataout, //   dout.export
		input  wire [0:0] datain,  //    din.export
		input  wire [0:0] oe,      //     oe.export
		inout  wire [0:0] padio    // pad_io.export
	);

	IOBUF_altera_gpio_1930_alkbnhy gpio_0 (
		.dataout (dataout), //  output,  width = 1,   dout.export
		.datain  (datain),  //   input,  width = 1,    din.export
		.oe      (oe),      //   input,  width = 1,     oe.export
		.padio   (padio)    //   inout,  width = 1, pad_io.export
	);

endmodule
