// rom.v

// Generated using ACDS version 20.2 50

`timescale 1 ps / 1 ps
module rom (
		output wire [31:0] q,       //       q.dataout
		input  wire [10:0] address, // address.address
		input  wire        clock,   //   clock.clk
		input  wire        rden     //    rden.rden
	);

	rom_rom_1port_2010_eadblwq rom_1port_0 (
		.q       (q),       //  output,  width = 32,       q.dataout
		.address (address), //   input,  width = 11, address.address
		.clock   (clock),   //   input,   width = 1,   clock.clk
		.rden    (rden)     //   input,   width = 1,    rden.rden
	);

endmodule
